### ISSUE TITLE
Memoria

### ISSUE THREAD

**Issue by vicase** [SihamTabik/Foro_Grupo_Estructura_de_Datos_A2#3]
Buenas noches, una última preguntilla sobre la práctica. Pone que hay que entregar una memoria sobre la práctica, hemos hecho un readme comentando un par de aspectos acerca de cómo usar las funciones extra. ¿Hay que comentar algo más(implementación o algo)? Gracias y un saludo

**Comment by SihamTabik** [comment]
Hola,

Antes de nada feliz año nuevo.
En el guión se especifica que hay que entregar memoria:
"​Entregar​ ​una​ ​memoria​ ​donde​ ​se​ ​describa​ ​la​ ​solución​ ​propuesta​ ​y​ ​cualquier​ ​mejora,​ ​en​ ​su  caso,​ ​que​ ​haya​ ​sido​ ​implementada​ ​para​ ​construir​ ​el​ ​árbol​ ​de​ ​preguntas."

Saludos.
Siham

**Comment by vicase** [comment]
Hola, feliz año. De acuerdo, gracias y un saludo
